#!/usr/bin/env python3
"""Check the built ROM against the pages the firmware rewrites, then embed it as firmware/generated/rom.h.
    mkromh.py <controller.gb> <rom.h>
"""
import os
import re
import sys

BANK = 16384
ROM_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "rom")

# Bank 0 files: they read $4000+ or run the bank switch, so they must never get a #pragma bank.
BANK0 = ["main", "mbox", "ui", "menu", "input", "catalog", "slots", "art", "mapinfo", "scr_emu", "theme"]

# The firmware writes these under the running console, so the image must leave them $FF.
PAGES = [(0x0010, 0x10, "the status block"),
         (0x0200, 0x100, "the config mirror"),
         (0x0300, 0x100, "the driver catalog"),
         (0x0400, 0x100, "the ROM slot page"),
         (0x0500, 0x200, "the map-target page"),
         (0x4000, 0x4000, "bank 1, the firmware window")]


def fail(msg):
    sys.exit("mkromh: " + msg)


def main():
    if len(sys.argv) != 3:
        fail("usage: mkromh.py <controller.gb> <rom.h>")
    src, out = sys.argv[1:]
    rom = open(src, "rb").read()
    if len(rom) not in (32768, 65536, 131072, 262144):
        fail("ROM is %d bytes; the cart holds 32-256 KB" % len(rom))

    for f in BANK0:
        if re.search(r"^#pragma bank", open(os.path.join(ROM_DIR, f + ".c")).read(), re.M):
            fail("rom/%s.c must stay in bank 0" % f)

    # A byte test, not a map test: sdld reports every ABS area (crt0, RST vectors) at address 0.
    for addr, n, what in PAGES:
        if any(b != 0xFF for b in rom[addr:addr + n]):
            fail("ROM has content in %s ($%04X-$%04X)" % (what, addr, addr + n - 1))

    banks = len(rom) // BANK
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w") as f:
        f.write("// generated by tools/mkromh.py from rom/ — do not edit\n")
        f.write("#define GB_ROM_BANKS %d\n" % banks)
        f.write("const unsigned int gb_rom_banks = %d;\n" % banks)
        f.write('const unsigned char __attribute__((aligned(4), section(".flashdata.gbrom"))) '
                "gb_rom[%d][%d] = {\n" % (banks, BANK))
        for b in range(banks):
            f.write("{\n")
            chunk = rom[b * BANK:(b + 1) * BANK]
            for i in range(0, BANK, 12):
                f.write("  " + ", ".join("0x%02x" % v for v in chunk[i:i + 12]) + ",\n")
            f.write("},\n")
        f.write("};\n")
    print("rom.h: %d x %d bytes" % (banks, BANK))


main()
