#!/usr/bin/env python3
"""rom/canvas.c's own tiles: the box frame, drawn here as 8x8 art and emitted as 2bpp beside the
GBDK console font (tile 0x80+).
    mktiles.py <generated-dir>
"""
import os
import sys

BASE = 0x80

# '.' background, '3' black. The corner is drawn once and mirrored; the box is an outer line, a
# one-pixel gap and an inner line, two pixels in from the cell.
BOX_TL = ["....3333",
          "...3....",
          "..3.3333",
          "..3.3...",
          "..3.3...",
          "..3.3...",
          "..3.3...",
          "..3.3..."]
BOX_T = ["33333333",
         "........",
         "33333333",
         "........",
         "........",
         "........",
         "........",
         "........"]
BOX_L = ["..3.3..."] * 8


def flip_h(a):
    return [r[::-1] for r in a]


def flip_v(a):
    return a[::-1]


def tile2bpp(art):
    out = []
    for row in art:
        lo = hi = 0
        for x, c in enumerate(row):
            v = 0 if c == "." else int(c)
            lo |= (v & 1) << (7 - x)
            hi |= (v >> 1) << (7 - x)
        out += [lo, hi]
    return out


BOX = [("BOX_TL", BOX_TL),
       ("BOX_T", BOX_T),
       ("BOX_TR", flip_h(BOX_TL)),
       ("BOX_L", BOX_L),
       ("BOX_R", flip_h(BOX_L)),
       ("BOX_BL", flip_v(BOX_TL)),
       ("BOX_B", flip_v(BOX_T)),
       ("BOX_BR", flip_h(flip_v(BOX_TL)))]


def emit(gen, stem, prefix, array, base, tiles, tool):
    guard = stem.upper() + "_H"
    os.makedirs(gen, exist_ok=True)
    with open(os.path.join(gen, stem + ".h"), "w") as f:
        f.write("// generated by %s — do not edit\n#ifndef %s\n#define %s\n\n" % (tool, guard, guard))
        f.write("#include <stdint.h>\n\n#define %sBASE 0x%02X\n" % (prefix, base))
        for i, (name, _) in enumerate(tiles):
            f.write("#define %s%-10s 0x%02X\n" % (prefix, name, base + i))
        f.write("\n#define %sCOUNT %u\nextern const uint8_t %s[];\n\n#endif\n" % (prefix, len(tiles), array))
    with open(os.path.join(gen, stem + ".c"), "w") as f:
        f.write("// generated by %s — do not edit\n#include <stdint.h>\n\n" % tool)
        f.write("const uint8_t %s[] = {\n" % array)
        for name, art in tiles:
            f.write("    " + "".join("0x%02X," % v for v in tile2bpp(art)) + "  // %s\n" % name)
        f.write("};\n")
    print("tiles: %u in %s/%s.c" % (len(tiles), gen, stem))


if __name__ == "__main__":
    emit(sys.argv[1] if len(sys.argv) > 1 else "generated", "cv_tiles", "CV_T_", "k_cv_tiles",
         BASE, BOX, "tools/mktiles.py")
